#!/usr/bin/env bash
# task1

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "ubuntu":"ubuntu" /var/www/html/index.nginx-debian.html
sudo chmod -R 777 /var/www 
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
