#!/usr/bin/env bash
# task3

sudo apt-get update
sudo apt-get upgrate
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/;
sudo chmod -R 755 /etc/nginx/sites-available/default;
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html;
echo "Holberton School" > /var/www/html/index.nginx-debian.html;
printf %s "server {
        listen 80 default_server;
	    root   /usr/share/nginx/html;
	    index  index.html index.htm;
        error_page 404 /404.html;
        location = /custom_404.html {
                root /usr/share/nginx/html;
                internal;
        }
        location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}
        }" > /etc/nginx/sites-available/default
sudo service nginx restart
