#!/usr/bin/env bash
#task9
echo "$$" >> /var/run/holbertonscript.pid
trap "rm  -rf /var/run/holbertonscript.pid ; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command' ;rm -rf /var/run/holbertonscript.pid ; exit" SIGTERM
while 'true'
do
echo "To infinity and beyond"
sleep 2
done
