#!/usr/bin/env bash
# fizzbuzz
IFS=':'
while read -r a pass uid b uinfo path shit
do
  echo "The user $a is part of the $b gang, lives in $path and rides $shit. $uid's place is protected by the passcode $pass, more info about the user here: $uinfo"
done </etc/passwd
