#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
f=holbertonschool
if [ -f "$f" ]
    then
    echo "$f file exists"
    if [ -s "$f" ]
        then
        echo "$f file is not empty"
    else
        echo "$f file is empty"
    fi
    echo "$f is a regular file"
else 
    echo "$f file does not exist"
fi