#!/usr/bin/env bash
#changing ip from home
sudo cp /etc/hosts ~/hosts.new
sudo sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
sudo echo "facebook.com 8.8.8.8" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
