#!/usr/bin/env bash
# run ngninx as not root
pkill nginx
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
